apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - image: 851557167064.dkr.ecr.ap-northeast-2.amazonaws.com/bastion:4
        name: test-tomcat
