apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - image: 851557167064.dkr.ecr.ap-northeast-2.amazonaws.com/bastion:5
        name: test-main
