apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
      - image: 851557167064.dkr.ecr.ap-northeast-2.amazonaws.com/bastion:event2
        name: event

